apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubernetes-bootcamp
  name: kubernetes-bootcamp
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernetes-bootcamp
  type: NodePort
status:
  loadBalancer: {}
